name: 'dbt_project'
version: '1.0'

profile: 'Snowflake'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt:
    staging:
      +materialized: table
    marts:
      +materialized: table
