name: kc_demo
version: '1.0'

profile: 'snowflake_demo'

model-paths: ["kc_demo/models"]

clean-targets: ["target", "dbt_modules"]

models:
  kc_demo:
    staging:
      +materialized: table
    marts:
      +materialized: table